package org.usfirst.frc771.TestingMyCommand.subsystems;

import org.usfirst.frc771.TestingMyCommand.Robot;
import org.usfirst.frc771.TestingMyCommand.RobotMap;
import org.usfirst.frc771.TestingMyCommand.commands.*;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc771.TestingMyCommand.OI;


public class Intake extends Subsystem {
//	private final Compressor compressor1 = RobotMap.pneumaticsCompressor1;
//    private final DoubleSolenoid doubleSolenoid1 = RobotMap.pneumaticsDoubleSolenoid1;
//    private final DoubleSolenoid doubleSolenoid2 = RobotMap.pneumaticsDoubleSolenoid2;
    
    int Caidel = 0;
    
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());     
    }
    
    public void Extend() {	
//    	doubleSolenoid1.set(DoubleSolenoid.Value.kForward);
//    	doubleSolenoid2.set(DoubleSolenoid.Value.kForward);
    }
    
    public void Retract() {
//    	doubleSolenoid1.set(DoubleSolenoid.Value.kReverse);
//    	doubleSolenoid2.set(DoubleSolenoid.Value.kReverse);
    }
    
    public void setCaidel(int value){
    	Caidel = value;
    }
    
    
    public int getCaidel(){
    	return Caidel;
    }
    
    
}
